name: gds
# either manually started, or on a schedule
on: [ push, workflow_dispatch ]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  gds:
    env:
        PDK_ROOT:       /home/runner/pdk
        PDK:            sky130A

    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install build-essential git csh libcairo2-dev tcl-dev tk-dev pip -y

    # PDK setup with volare
    - name: PDK Setup
      run: |
        pip install volare
        volare enable e8294524e5f67c533c5d0c3afa0bcc5b2a5fa066 

    # Build and install magic
    - name: magic Setup
      run: |
        git clone --branch 8.3.311 https://github.com/RTimothyEdwards/magic
        cd magic && ./configure --with-cairo=no --disable-readline --without-x && make && sudo make install

    # run magic to build the GDS
    - name: make GDS
      run: make

    - name: Copy GDS
      run: |
        mkdir -p runs/wokwi/results/final/gds runs/wokwi/results/final/lef runs/wokwi/results/final/verilog/gl
        cp gds/skullart.gds runs/wokwi/results/final/gds
        cp gds/skullart.lef runs/wokwi/results/final/lef
        cp src/skullart.gl.v runs/wokwi/results/final/verilog/gl/skullart.v

    # for debugging, show all the files
    - name: show files
      run: find runs/wokwi/

    - name: populate src cache
      uses: actions/cache@v3
      with:
        path: src
        key: ${{ runner.os }}-src-${{ github.run_id }}

    - name: populate runs cache
      uses: actions/cache@v3
      with:
        path: runs
        key: ${{ runner.os }}-runs-${{ github.run_id }}

  png:
    needs: gds
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: restore runs cache
      uses: actions/cache@v3
      with:
        path: runs
        key: ${{ runner.os }}-runs-${{ github.run_id }}

    - name: create svg
      run: |
        python -m pip install gdstk
        python << EOF
        import gdstk
        import pathlib

        gds = sorted(pathlib.Path('runs').glob('wokwi/results/final/gds/*.gds'))
        library = gdstk.read_gds(gds[-1])
        top_cells = library.top_level()
        top_cells[0].write_svg('gds_render.svg')
        EOF

    - name: convert to png
      run: |
        python -m pip install cairosvg
        python << EOF
        import cairosvg
        cairosvg.svg2png(url='gds_render.svg', write_to='gds_render.png')
        EOF

    - name: populate png cache
      uses: actions/cache@v3
      with:
        path: 'gds_render.png'
        key: ${{ runner.os }}-png-${{ github.run_id }}

  viewer:
    needs: gds
    runs-on: ubuntu-latest
    steps:
    - name: checkout GDS2glTF repo
      uses: actions/checkout@v3
      with:
        repository: mbalestrini/GDS2glTF

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: restore runs cache
      uses: actions/cache@v3
      with:
        path: runs
        key: ${{ runner.os }}-runs-${{ github.run_id }}

    - name: gds2gltf
      run: |
        python -m pip install numpy gdspy triangle pygltflib
        cp runs/wokwi/results/final/gds/*.gds tinytapeout.gds
        python3 gds2gltf.py tinytapeout.gds

    - name: populate viewer cache
      uses: actions/cache@v3
      with:
        path: 'tinytapeout.gds.gltf'
        key: ${{ runner.os }}-viewer-${{ github.run_id }}

  artifact:
    needs:
    - gds
    runs-on: ubuntu-latest
    steps:
    - name: restore src cache
      uses: actions/cache@v3
      with:
        path: src
        key: ${{ runner.os }}-src-${{ github.run_id }}

    - name: restore runs cache
      uses: actions/cache@v3
      with:
        path: runs
        key: ${{ runner.os }}-runs-${{ github.run_id }}

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
          # path depends on the tag and the module name
          name: GDS
          path: |
            src/*
            runs/wokwi/results/final/*
            runs/wokwi/reports/metrics.csv
            runs/wokwi/reports/synthesis/1-synthesis.AREA 0.stat.rpt

  pages:
    needs:
    - png
    - viewer
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: restore png cache
      uses: actions/cache@v3
      with:
        path: 'gds_render.png'
        key: ${{ runner.os }}-png-${{ github.run_id }}
    - name: restore viewer cache
      uses: actions/cache@v3
      with:
        path: 'tinytapeout.gds.gltf'
        key: ${{ runner.os }}-viewer-${{ github.run_id }}
    - name: generate redirect to viewer
      run: |
        cat << EOF >> index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Redirecting to GDS Viewer...</title>
          </head>
          <body>
            <script>
              location.href = "https://gds-viewer.tinytapeout.com/?model=" + encodeURIComponent(location.href + '/tinytapeout.gds.gltf');
            </script>
          </body>
          </html>
        EOF
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: '.'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1.2.2

  preview:
    needs: pages
    runs-on: ubuntu-latest
    steps:
    - name: add gds preview
      run: |
        PAGE_URL=${{ needs.pages.outputs.page_url }}
        PAGE_URL=$(echo "$PAGE_URL" | sed -e 's/\/$//')
        cat << EOF >> $GITHUB_STEP_SUMMARY
        # layout
        ![png]($PAGE_URL/gds_render.png)
        # viewer
        [open preview](https://gds-viewer.tinytapeout.com/?model=$PAGE_URL/tinytapeout.gds.gltf)
        EOF
